create table "public"."message" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone default now(),
    "author" uuid not null,
    "text" text
);


alter table "public"."message" enable row level security;

alter table "public"."user_profiles" add column "profile_img_url" text;

CREATE UNIQUE INDEX message_pkey ON public.message USING btree (id);

CREATE UNIQUE INDEX user_profiles_profile_img_url_key ON public.user_profiles USING btree (profile_img_url);

alter table "public"."message" add constraint "message_pkey" PRIMARY KEY using index "message_pkey";

alter table "public"."message" add constraint "message_author_fkey" FOREIGN KEY (author) REFERENCES user_profiles(id) not valid;

alter table "public"."message" validate constraint "message_author_fkey";

alter table "public"."user_profiles" add constraint "user_profiles_profile_img_url_key" UNIQUE using index "user_profiles_profile_img_url_key";


