create table "public"."books" (
    "id" bigint generated by default as identity not null,
    "title" text,
    "author" text,
    "created_at" timestamp with time zone default now()
);


alter table "public"."books" enable row level security;

create table "public"."meetings" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone default now(),
    "meeting_date" timestamp with time zone not null,
    "book" bigint
);


alter table "public"."meetings" enable row level security;

create table "public"."rsvps" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone default now(),
    "meeting" bigint not null,
    "is_attending" boolean not null,
    "user" uuid
);


alter table "public"."rsvps" enable row level security;

create table "public"."user_profiles" (
    "id" uuid not null,
    "created_at" timestamp with time zone default now(),
    "display_name" text
);


alter table "public"."user_profiles" enable row level security;

CREATE UNIQUE INDEX meeting_meeting_date_key ON public.meetings USING btree (meeting_date);

CREATE UNIQUE INDEX meeting_pkey ON public.meetings USING btree (id);

CREATE UNIQUE INDEX reading_pkey ON public.books USING btree (id);

CREATE UNIQUE INDEX rsvp_pkey ON public.rsvps USING btree (id);

CREATE UNIQUE INDEX user_profile_pkey ON public.user_profiles USING btree (id);

alter table "public"."books" add constraint "reading_pkey" PRIMARY KEY using index "reading_pkey";

alter table "public"."meetings" add constraint "meeting_pkey" PRIMARY KEY using index "meeting_pkey";

alter table "public"."rsvps" add constraint "rsvp_pkey" PRIMARY KEY using index "rsvp_pkey";

alter table "public"."user_profiles" add constraint "user_profile_pkey" PRIMARY KEY using index "user_profile_pkey";

alter table "public"."meetings" add constraint "meeting_meeting_date_key" UNIQUE using index "meeting_meeting_date_key";

alter table "public"."meetings" add constraint "meetings_book_fkey" FOREIGN KEY (book) REFERENCES books(id) not valid;

alter table "public"."meetings" validate constraint "meetings_book_fkey";

alter table "public"."rsvps" add constraint "rsvps_meeting_fkey" FOREIGN KEY (meeting) REFERENCES meetings(id) not valid;

alter table "public"."rsvps" validate constraint "rsvps_meeting_fkey";

alter table "public"."rsvps" add constraint "rsvps_user_fkey" FOREIGN KEY ("user") REFERENCES user_profiles(id) not valid;

alter table "public"."rsvps" validate constraint "rsvps_user_fkey";

alter table "public"."user_profiles" add constraint "user_profiles_id_fkey" FOREIGN KEY (id) REFERENCES auth.users(id) not valid;

alter table "public"."user_profiles" validate constraint "user_profiles_id_fkey";


